# Generated by Django 5.1.2 on 2024-10-21 04:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0005_remove_feehistory_transaction_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feehistory',
            name='payment_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
