# Generated by Django 5.1.2 on 2024-10-22 10:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0006_alter_feehistory_payment_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(blank=True, choices=[('admin', 'Admin'), ('staff', 'Office Staff'), ('librarian', 'Librarian')], max_length=10, null=True),
        ),
    ]
